package sjsu.edu.cs151.PennySight;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * This class the initial application class that generated by the Spring Boot Initializr
 * @author PennySight
 */
@SpringBootTest
class PennySightApplicationTests {

    @Test
    void contextLoads() {
    }

}
